version: "3.9"
services:
  telegram_bot:
    build: telegram_bot/
    environment:
      MONGO_USER: "${MONGO_ROOT_USERNAME}"
      MONGO_PASS: "${MONGO_ROOT_PASSWORD}"
    entrypoint: python3 /app/bot.py

  mongo:
    image: "mongo:focal"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD}"

volumes:
  mongo_data:
