version: "3.9"
services:
  web:
    build: web/
    ports:
      - "88:80"
    entrypoint: python3 /app/main.py

  redis:
    image: "redis:bullseye"

  telegram_bot:
    build: telegram_bot/
    environment:
      MONGO_USER: "${MONGO_ROOT_USERNAME}"
      MONGO_PASS: "${MONGO_ROOT_PASSWORD}"
      TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"
    entrypoint: python3 /app/telegram_bot.py
    depends_on:
      - "mongo"
      - "redis"

  mongo:
    image: "mongo:focal"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD}"
    ports:
      - 27017:27017
    expose:
      - 27017:27017

  image_downloader:
    build: image_downloader/
    entrypoint: python3 /app/img.py
    depends_on:
      - "redis"

volumes:
  mongo_data:
