version: "3.9"
services:
  web:
    restart: unless-stopped
    build: web/
    ports:
      - "88:8080"

  redis:
    restart: unless-stopped
    image: "redis:bullseye"

  telegram_bot:
    restart: unless-stopped
    build: telegram_bot/
    environment:
      MONGO_USER: "${MONGO_ROOT_USERNAME}"  
      MONGO_PASS: "${MONGO_ROOT_PASSWORD}"
      TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"
    depends_on:
      - "mongo"
      - "redis"

  mongo:
    restart: unless-stopped
    image: "mongo:focal"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD}"

  image_downloader:
    restart: unless-stopped
    build: image_downloader/
    depends_on:
      - "redis"

volumes:
  mongo_data:
